Chatbot Intention Classifier/Python_Code/cloud_dev/Home/models.py
# Libraries & Packages##################################################################
from flask_login import UserMixin
from cloud_dev import db
########################################################################################
'''
This modules handles the creation of the db model.

This code is adapted to my project following the tutorial.

I confirm that the Source code belongs to:

https://scotch.io/tutorials/authentication-and-authorization-with-flask-login


'''

class User(UserMixin,db.Model):
    id = db.Column(db.Integer, primary_key=True) # primary keys are required by SQLAlchemy
    email = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(100))
    name = db.Column(db.String(10))

Chatbot Intention Classifier/Python_Code/cloud_dev/Home/auth.py
# lIBRARIES & PACKAGES#########################################################
from flask import Blueprint, render_template, redirect, url_for, request, flash
from werkzeug.security import generate_password_hash, check_password_hash
from cloud_dev import db
from flask_login import login_user, logout_user, login_required
from .models import User
###############################################################################
'''
This modules handles the views, login, signup, signout and validates
the user in the database. Also applying hash security to the password.

This code is adapted to my project following the tutorial.

I confirm that the Source code belongs to:

https://scotch.io/tutorials/authentication-and-authorization-with-flask-login


'''
auth = Blueprint('auth', __name__)

@auth.route('/login')
def login():
     return render_template('login.html')

@auth.route('/login', methods=['POST'])
def login_post():
    email = request.form.get('email')
    password = request.form.get('password')
    remember = True if request.form.get('remember') else False

    user = User.query.filter_by(email=email).first()

    
    if not user or not check_password_hash(user.password, password): 
        flash('Please check your login details and try again.')
        return redirect(url_for('auth.login'))

    
    login_user(user, remember=remember)
    return render_template("chatbot.html")

@auth.route('/signup')
def signup():
    return render_template('signup.html')

@auth.route('/signup', methods=['POST'])
def signup_post():
    email = request.form.get('email')
    name = request.form.get('name')
    password = request.form.get('password')

    user = User.query.filter_by(email=email).first() 
    if user:
        flash('Email address already exists')
        return redirect(url_for('auth.signup'))

    
    new_user = User(email=email, name=name, password=generate_password_hash(password, method='sha256'))

    
    db.session.add(new_user)
    db.session.commit()

    return redirect(url_for('auth.login'))

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('home.homepage'))

Chatbot Intention Classifier/Python_Code/cloud_dev/Home/routes.py
#Libraries & Packages##################################################
from flask import Blueprint, render_template, redirect, url_for
from flask_login import login_required, current_user
from cloud_dev import db
########################################################################
'''
This modules handles the views for homepage and profile.

This code is adapted to my project following the tutorial.

I confirm that the Source code belongs to:

https://scotch.io/tutorials/authentication-and-authorization-with-flask-login


'''

home = Blueprint('home', __name__,template_folder='templates')

@home.route('/homepage')
def homepage():
    return render_template('home.html')
    #return redirect(url_for('main.chatbot'))
@home.route('/profile')
@login_required
def profile():
    return render_template('profile.html', name=current_user.name)
    #return redirect(url_for('main.chatbot')
    #return render_template('chatbot.html', name=current_user.name)

Chatbot Intention Classifier/Python_Code/cloud_dev/Home/templates/base.html
<!-- This template is adapted using the tutorial. I confirm that the sources code belongs to https://scotch.io/tutorials/authentication-and-authorization-with-flask-login-->

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Flask Auth Example</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />
</head>

<body>
    <section class="hero is-info is-fullheight">

        <div class="hero-head">
            <nav class="navbar">
                <div class="container">

                    <div id="navbarMenuHeroA" class="navbar-menu">
                        <div class="navbar-end">
                            <a href="{{ url_for('home.homepage') }}" class="navbar-item">
                                Home
                            </a>
                            <a href="{{ url_for('home.profile') }}" class="navbar-item">
                                Profile
                            </a>
                            <a href="{{ url_for('auth.login') }}" class="navbar-item">
                                Login
                            </a>
                            <a href="{{ url_for('auth.signup') }}" class="navbar-item">
                                Sign Up
                            </a>
                            <a href="{{ url_for('auth.logout') }}" class="navbar-item">
                                Logout
                            </a>
                            <a href="{{ url_for('main.chatbot') }}" class="navbar-item">
                                Chatbot
                            </a>
                        </div>
                    </div>
                </div>
            </nav>
        </div>

        <div class="hero-body">
            <div class="container has-text-centered">
               {% block content %}
               {% endblock %}
            </div>
        </div>
    </section>
</body>

</html>

Chatbot Intention Classifier/Python_Code/cloud_dev/Home/templates/home.html
<!-- templates/index.html -->

{% extends "base.html" %}

{% block content %}
<h1 class="title">
  Flask Login Example
</h1>
<h2 class="subtitle">
  Easy authentication and authorization in Flask.
</h2>
{% endblock %}

Chatbot Intention Classifier/Python_Code/cloud_dev/Home/templates/login.html
{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Login</h3>
    <div class="box">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="notification is-danger">
                {{ messages[0] }}
            </div>
        {% endif %}
        {% endwith %}
        <form method="POST" action="/login">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="email" name="email" placeholder="Your Email" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="password" name="password" placeholder="Your Password">
                </div>
            </div>
            <div class="field">
                <label class="checkbox">
                    <input type="checkbox">
                    Remember me
                </label>
            </div>
            <button class="button is-block is-info is-large is-fullwidth">Login</button>
        </form>
    </div>
</div>
{% endblock %}

Chatbot Intention Classifier/Python_Code/cloud_dev/Home/templates/profile.html
<!-- templates/profile.html -->

{% extends "base.html" %}

{% block content %}
<h1 class="title">
    Welcome, {{ name }}!
  </h1>
{% endblock %}

Chatbot Intention Classifier/Python_Code/cloud_dev/Home/templates/signup.html
<!-- templates/signup.html -->

{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Sign Up</h3>
    <div class="box">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="notification is-danger">
                    {{ messages[0] }}. Go to <a href="{{ url_for('auth.login') }}">login page</a>.
            </div>
        {% endif %}
        {% endwith %}
        <form action="/signup" method="POST" action="/signup">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="email" name="email" placeholder="Email" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="name" placeholder="Name" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="password" name="password" placeholder="Password">
                </div>
            </div>

            <button class="button is-block is-info is-large is-fullwidth">Sign Up</button>
        </form>
    </div>
</div>
{% endblock %}